services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    env_file:
      - .env
    volumes:
        - ./configs/config.yaml:/app/configs/config.yaml

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notifications
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --requirepass ${NS_REDIS_PASSWORD:-redis_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      REDIS_PASSWORD: ${NS_REDIS_PASSWORD:-redis_password}
    healthcheck:
      test: [ "CMD", "redis-cli", "--pass", "${NS_REDIS_PASSWORD:-redis_password}", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  nats:
    image: nats:2.10
    container_name: nats
    ports:
      - "4222:4222"
    command:
      - "-js"
      - "-DV"
      - "--logtime"

volumes:
  postgres_data:
  redis_data:
    driver: local