server:
  port: "8080"
  read_timeout: 5s
  write_timeout: 5s

database:
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 1h

logs:
  logs_level: "debug"

broker_type: "kafka"
nats:
  subject_new: "notifications_new"
  subject_read: "notifications.read"
kafka:
  brokers:
    - "kafka:9092"
  topic: "notifications"