server:
  port: "8080"
  read_timeout: 5s
  write_timeout: 5s

database:
  max_open_conns: 12
  max_idle_conns: 4
  conn_max_lifetime: 30m

logs:
  logs_level: "warn"

broker_type: "nats"
nats:
  subject_new: "notifications_new"
  subject_read: "notifications.read"
kafka:
  brokers:
    - "kafka:9092"
  topic: "notifications"