server:
  port: "8080"
  read_timeout: 5s
  write_timeout: 5s

database:
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  db: 0
  pool_size: 10
  default_ttl: 24
  high_ttl: 0
  unread_key_prefix: "user:%s:unread"

nats:
  subject_new: "notifications.new"
  subject_read: "notifications.read"

notifications:
  default_priority: "medium"