server:
  port: "8081"
  read_timeout: 5s
  write_timeout: 5s

database:
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 1h

redis:
  db: 0
  pool_size: 10
  default_ttl: 30
  high_ttl: 0
  unread_key_prefix: "user:%s:unread"
  broadcast_channel: "notifications:broadcast"

logs:
  logs_level: "debug"

broker_type: "kafka"
nats:
  subject_new: "notifications_new"
  subject_read: "notifications.read"
kafka:
  brokers:
    - "kafka:9092"
  topic: "notifications"
  consumer_group: "ws-notifier"